(library (chez-swank)
  (export start-swank)
  (import (rename (chezscheme)
                  (bytevector-copy! %bytevector-copy!)
                  (load %load)
                  (error %error)
                  (with-output-to-string %with-output-to-string) ;; (utf8->string %utf8->string) (string->utf8 %string->utf8)
                  ) (socket net))
  (include "specific/chez.ss")
  (include "common/base.scm")
  (include "common/handlers.scm"))
