(define-library (guile-swank)
  (import (scheme base)
          (scheme write)
          (scheme case-lambda)
          (scheme read)
          (scheme char)
          (scheme eval)
          (ice-9 match)
          (ice-9 binary-ports)
          (ice-9 documentation)
          (srfi srfi-69)
          (srfi srfi-11) ;; let-values
          (srfi srfi-1)
          (srfi srfi-9)
          (ice-9 pretty-print))
  (export start-swank swank:lookup-presented-object
          swank:lookup-presented-object-or-lose)

  (include "specific/guile.scm")
  (include "common/base.scm")
  (include "common/handlers.scm")
  )
