(require 'socket)
(define ($scheme-name)
  "larceny")
(define ($all-package-names)
  '())

(define $make-hash-table make-hash-table)
(define $hash-table/get hash-table-ref/default)
(define $hash-table/put! hash-table-set!)
(define ($error-description error)
  (let ((o (open-output-string)))
    (display error o)
    (get-output-string o)))
(define ($open-tcp-server/accept port-number handler)
  (let ((s (make-server-socket port-number 'blocking)))
    (let-values (((ns addr) (server-socket-accept s)))
      (let ((in (socket-input-port ns 'blocking 'char))
            (out (socket-output-port ns 'blocking 'char 'flush)))
        (handler port-number in out)))))
